nodeLinker: node-modules

npmScopes:
  commercetools:
    npmAlwaysAuth: true
    npmRegistryServer: "https://brave-suitable-snapper.ngrok-free.app"
    npmPublishRegistry: "https://brave-suitable-snapper.ngrok-free.app"
  commercetools-cli:
    npmAlwaysAuth: true
    npmRegistryServer: "https://brave-suitable-snapper.ngrok-free.app"
    npmPublishRegistry: "https://brave-suitable-snapper.ngrok-free.app"
