nodeLinker: node-modules

npmScopes:
  commercetools:
    npmRegistryServer: "https://brave-suitable-snapper.ngrok-free.app/"
  commercetools-cli:
    npmRegistryServer: "https://brave-suitable-snapper.ngrok-free.app/"
