nodeLinker: node-modules

npmScopes:
  commercetools:
    npmAlwaysAuth: true
    npmRegistryServer: "https://"
    npmPublishRegistry: "https://"
  commercetools-cli:
    npmAlwaysAuth: true
    npmRegistryServer: "https://"
    npmPublishRegistry: "https://"
